version: '3'
services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  web-crawler:
    build:
      context: .
    depends_on:
      - selenium-chrome
  
  stdin_open: true
  tty: true
